### PR TITLE
fix failpoints test

### LINKED ISSUE #826: Indexing failpoints tests are broken
The tests do not compile.

### PR DESCRIPTION
**Pull request by PSeitz**
fix failpoints test

fixes #826

### CODE REVIEW

File: quickwit-indexing/failpoints/mod.rs [hunk 1]
```diff
@@ -258,7 +260,10 @@ async fn test_merge_executor_controlled_directory_kill_switch() -> anyhow::Resul
 
     let metastore = test_index_builder.metastore();
     let split_infos = metastore.list_all_splits(index_id).await?;
```
Comment (guilload) [inline quickwit-indexing/failpoints/mod.rs:262]: `split_infos` -> `splits`
`splits` -> `split_metadatas`

**Review by guilload — APPROVED** [review]
Thanks for the fix.

**Review by fulmicoton — APPROVED** [review]

File: quickwit-indexing/failpoints/mod.rs (hunk 1 above)
Comment (fulmicoton) [reply quickwit-indexing/failpoints/mod.rs:262]: Let's do the rename somewhere else.
