### PR TITLE
Fix packager timeout due to file bundle creation

### LINKED ISSUE #488: Packager timeout due to file bundle creation which takes more than a hearbeat

### PR DESCRIPTION
**Pull request by fmassot**
fixes #488

### CODE REVIEW

**Review by evanxg852000 — APPROVED** [review]

File: quickwit-indexing/src/actors/packager.rs [hunk 1]
```diff
@@ -136,8 +136,10 @@ fn create_file_bundle(
     segment_metas: &[SegmentMeta],
     scratch_dir: &ScratchDirectory,
     split_file: &mut impl io::Write,
+    ctx: &ActorContext<IndexedSplit>,
 ) -> anyhow::Result<Range<u64>> {
-    // create bundle
+    info!("create-file-bundle");
```
[the remark this answers is not in the document]
Comment (fulmicoton) [reply quickwit-indexing/src/actors/packager.rs:141]: +1

File: quickwit-indexing/src/actors/packager.rs [hunk 2]
```diff
@@ -157,7 +158,7 @@ fn merge_segments_if_required(
     split: &mut IndexedSplit,
     ctx: &ActorContext<IndexedSplit>,
 ) -> anyhow::Result<Vec<SegmentMeta>> {
-    info!("merge-segments-if-required");
+    debug!(index=%split.index_id, split=?split, "merge-segments-if-required");
```
Comment (guilload) [inline quickwit-indexing/src/actors/packager.rs:161]:
```suggestion
    debug!(index = %split.index_id, split = ?split, "merge-segments-if-required");
```

File: quickwit-indexing/src/actors/packager.rs [hunk 3]
```diff
@@ -186,19 +186,22 @@ fn build_hotcache<W: io::Write>(
 fn create_packaged_split(
     segment_metas: &[SegmentMeta],
     split: IndexedSplit,
+    ctx: &ActorContext<IndexedSplit>,
 ) -> anyhow::Result<PackagedSplit> {
-    info!("create-packaged-split");
+    info!(split=?split, "create-packaged-split");
```
Comment (guilload) [inline quickwit-indexing/src/actors/packager.rs:191]:
```suggestion
    info!(split = ?split, "create-packaged-split");
```

File: quickwit-indexing/src/actors/packager.rs [hunk 4]
```diff
@@ -186,19 +186,22 @@ fn build_hotcache<W: io::Write>(
...
 
     let split_filepath = split.split_scratch_directory.path().join(BUNDLE_FILENAME); // TODO rename <split_id>.split
     let mut split_file = CountingWriter::wrap(File::create(split_filepath)?);
 
+    debug!(split=?split, "create-file-bundle");
```
Comment (guilload) [inline quickwit-indexing/src/actors/packager.rs:196]:
```suggestion
    debug!(split = ?split, "create-file-bundle");
```

**Review by guilload — APPROVED** [review]
