### PR TITLE
Rename old index_config to doc_mapper, fix failpoints tests and fetch index chekckpoint when spawning pipeline, add failpoint test to coverage

### LINKED ISSUE #1025: We don't fetch index checkpoint when we spawn the indexing pipeline
First, failpoints tests are really good. We definitely need to replug them into the CI. 

Here is the problem I got when doing this:
- spawn indexing pipeline
- pipeline publish a split
- an error occurred in the publisher just after publishing (thanks to failpoints)
- pipeline is restarted
- we now get the error `Publish checkpoint delta overlaps with the current checkpoint` as we don't fetch new checkpoints when we spawn the pipeline.

We need to remove transient data from `IndexingPipelineParams`, I think we just need to fetch index metadata from the metastore at each pipeline spawning.

ping @fulmicoton @guilload

### PR DESCRIPTION
**Pull request by fmassot**
Ok, now the PR title is too long... I ended doing all this in one PR everything was mixed up. I added some comments to guide you.

Fix: 
- [x] #1025
- [x] #1023 
- [x] #977 
- [x] #472

### CODE REVIEW

File: quickwit-indexing/src/actors/indexing_pipeline.rs [hunk 1]
```diff
@@ -389,8 +396,13 @@ impl IndexingPipeline {
             .spawn_sync();
 
         // Source
+        let source_checkpoint = index_metadata
```
Comment (fmassot) [inline quickwit-indexing/src/actors/indexing_pipeline.rs:399]: Here we now fetch the checkpoint from the metastore

File: quickwit-indexing/failpoints/mod.rs [hunk 2]
```diff
@@ -234,25 +216,40 @@ async fn test_merge_executor_controlled_directory_kill_switch() -> anyhow::Resul
     // This tests checks that if a merger is killed in a middle of
     // a merge, then the controlled directory makes it possible to
     // abort the merging operation and return quickly.
+    // NOTE(fmassot): This test is working but not as exactly we would want.
```
Comment (fmassot) [inline quickwit-indexing/failpoints/mod.rs:219]: I keep this test but it's not as useful as before as now we are just doing the merge in a protected zone.

File: .github/workflows/coverage.yml [hunk 3]
```diff
@@ -119,7 +119,10 @@ jobs:
 
       - name: Generate code coverage
         run: |
-          QW_ENV=LOCAL cargo +nightly llvm-cov --all-features --workspace --lcov --output-path lcov.info
+          cargo +nightly llvm-cov clean --workspace
```
Comment (fmassot) [inline .github/workflows/coverage.yml:122]: Should work according the docs https://github.com/taiki-e/cargo-llvm-cov

Comment (fmassot) [reply .github/workflows/coverage.yml:122]: I triggered manually the coverage here: https://github.com/quickwit-inc/quickwit/actions/runs/1655778045

File: quickwit-cli/tests/helpers.rs [hunk 4]
```diff
@@ -199,16 +199,8 @@ pub fn create_test_env(index_id: String, storage_type: TestStorageType) -> anyho
             (metastore_uri.to_string(), storage)
         }
     };
-
-    let index_uri = format!("{}/{}", metastore_uri, index_id);
     let index_config_path = resources_dir_path.join("index_config.yaml");
-    fs::write(
-        &index_config_path,
-        // A poor's man templating engine...
-        DEFAULT_INDEX_CONFIG
```
Comment (fmassot) [inline quickwit-cli/tests/helpers.rs:208]: this was obsolete

File: quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs [hunk 5]
```diff
@@ -547,9 +547,9 @@ mod tests {
```
Comment (fmassot) [inline quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs:547]: Only renaming in this file.

File: quickwit-doc-mapper/src/doc_mapper.rs [hunk 6]
```diff
@@ -113,21 +113,21 @@ mod tests {
     }
```
Comment (fmassot) [inline quickwit-doc-mapper/src/doc_mapper.rs:113]: Only renaming here too.

File: quickwit-doc-mapper/src/doc_mapper.rs [hunk 7]
```diff
@@ -113,21 +113,21 @@ mod tests {
...
 
     #[test]
-    fn test_sedeserialize_index_config() -> anyhow::Result<()> {
-        let deserialized_default_config =
+    fn test_sedeserialize_doc_mapper() -> anyhow::Result<()> {
```
Comment (evanxg852000) [inline quickwit-doc-mapper/src/doc_mapper.rs:116]:
```suggestion
    fn test_deserialize_serialize_doc_mapper() -> anyhow::Result<()> {
```

File: quickwit-indexing/failpoints/mod.rs [hunk 8]
```diff
@@ -234,25 +216,40 @@ async fn test_merge_executor_controlled_directory_kill_switch() -> anyhow::Resul
...
+    // Ideally we want the actor to stop while merging which is a long task and we
+    // don't want to wait until it's finished. But... the merging phase is
+    // currently in a protected zone and thus there will be not kill switch activated
+    // during this period. We added the protected zone because without we observe from
```
Comment (evanxg852000) [inline quickwit-indexing/failpoints/mod.rs:223]:
```suggestion
    // during this period. We added the protected zone because without it, we observe from
```

File: .github/workflows/coverage.yml (hunk 3 above)
Comment (evanxg852000) [reply .github/workflows/coverage.yml:122]: this run is still failling

**Review by evanxg852000 — APPROVED** [review]
Just left minor comments but it looks good to me overall.
