### PR TITLE
Improves Error handling and different bugs.

### LINKED ISSUE #269: Search server return 200 but log an ERROR
Request executed in browser on hdfs log dataset

```
http://quickwit-test-392975419.us-east-1.elb.amazonaws.com/api/v1/hdfs_logs/search?query=%22resource.18%22
```

or the curl command:
```bash
curl -v 'http://your-host/api/v1/hdfs_logs/search?query=%22datanode+12%22'  -H "Content-Type: application/json"
```

both gives:

```
Jul 11 11:10:51.577 ERROR quickwit_search::root: err=Failed to search a leaf node due to Status { code: InvalidArgument, message: "Invalid query: QueryParserError(The field '\"body\"' does not have positions indexed)", metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Sun, 11 Jul 2021 11:10:51 GMT"} } }
```

The error is expected but the server return a 200 with this result:

```json
{
  "numHits": 0,
  "hits": [],
  "numMicrosecs": 2944
}
```

### PR DESCRIPTION
**Pull request by fulmicoton**
Closes #269.

SearchError are JSON serialized automatically by the grpc adapter.
Upon one leaf failure the whole request now fails (before it was just ignore the single leaf error).
We do not hold the search pool lock forever in the root and in the assign_client method.

### CODE REVIEW

File: quickwit-search/src/root.rs [hunk 1]
```diff
@@ -80,44 +82,33 @@ pub async fn root_search(
...
     debug!(assigned_leaf_search_jobs=?assigned_leaf_search_jobs, "Assigned leaf search jobs.");
 
-    let clients = client_pool.clients.read().await;
-
     // Create search request with start offset is 0 that used by leaf node search.
     let mut search_request_with_offset_0 = search_request.clone();
     search_request_with_offset_0.start_offset = 0;
     search_request_with_offset_0.max_hits += search_request.start_offset;
 
     // Perform the query phese.
```
Comment (fmassot) [inline quickwit-search/src/root.rs:90]: typo `phase`

**Review by fmassot — APPROVED** [review]
Great job as always fulmicoton! 

I think we can merge it but I have two things in mind:
- the tests are useless to check if the serialization/deserialization of errors is working well as we use the mocking service
- on the handling errors, it's worth noting that for some errors like invalid query, this is not useful to retry.
