### PR TITLE
Fix merge pipeline spawning & pipeline retry.

### LINKED ISSUE #992: quickwit index merge fails with Failed to create source `void-source`
when triggering a merge via cli I get this error `quickwit index merge --index hdfs --config=quickwit.yaml `

```
2021-12-28T18:12:13.242Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::index=hdfs gen=0}: quickwit_indexing::actors::indexing_pipeline: spawn-indexing-pipeline root_dir=./qwdata/indexing/hdfs/void-source merge_policy=StableMultitenantWithTimestampMergePolicy { demux_enabled: false, demux_factor: 8, demux_field_name: None, min_level_num_docs: 100000, merge_enabled: true, merge_factor: 10, max_merge_factor: 12, split_num_docs_target: 10000000 }
2021-12-28T18:12:13.242Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=hdfs gen=0}:{actor=GarbageCollector}: quickwit_indexing::actors::garbage_collector: garbage-collect-operation
2021-12-28T18:12:13.242Z ERROR {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}:: quickwit_indexing::actors::indexing_pipeline: Error while spawn_pipeline, waiting 1000ms err=Failed to create source `void-source` of type `void`. Cause: invalid type: map, expected unit struct VoidSourceParams

Caused by:
    invalid type: map, expected unit struct VoidSourceParams
2021-12-28T18:12:13.242Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{msg_id=1}:{index=hdfs gen=1}: quickwit_indexing::actors::indexing_pipeline: spawn-indexing-pipe
line root_dir=./qwdata/indexing/hdfs/void-source merge_policy=StableMultitenantWithTimestampMergePolicy { demux_enabled: false
```

### PR DESCRIPTION
**Pull request by fmassot**
Fix #992 

I fixed also the pipeline retry that was not working as expected.

### CODE REVIEW

File: quickwit-indexing/src/actors/indexing_pipeline.rs [hunk 1]
```diff
@@ -425,10 +427,10 @@ impl IndexingPipeline {
     // 3   16s
     // ...
     // >=8   5mn
-    fn wait_duration_before_retry(retry_count: usize) -> Option<Duration> {
+    fn wait_duration_before_retry(retry_count: usize) -> Duration {
         let mut wait_time_sec = 2_usize.pow(retry_count as u32 + 1);
```
Comment (guilload) [inline quickwit-indexing/src/actors/indexing_pipeline.rs:431]: This can overflow after approximately 5h30 ;)

File: quickwit-indexing/src/actors/indexing_pipeline.rs [hunk 2]
```diff
@@ -439,19 +441,17 @@ impl IndexingPipeline {
...
-                    IndexingPipelineMessage::Spawn {
-                        retry_count: retry_count + 1,
-                    },
-                )
-                .await;
-            } else {
-                return Err(ActorExitStatus::Failure(Arc::new(spawn_error)));
-            }
+            let duration_before_retry = Self::wait_duration_before_retry(retry_count);
+            error!(err=?spawn_error, "Error while spawn_pipeline, waiting 1000ms");
```
Comment (guilload) [inline quickwit-indexing/src/actors/indexing_pipeline.rs:447]: The error message is inaccurate. I'd go with something like:
```
 error!(err=?spawn_error, retry_count = .., retry_delay = .., "Error while spawning indexing pipeline, retrying after some time.");
 ```

File: quickwit-indexing/src/actors/indexing_server.rs [hunk 3]
```diff
@@ -320,16 +320,16 @@ impl IndexingServer {
     ) -> anyhow::Result<IndexingPipelineId> {
         let pipeline_id = IndexingPipelineId {
             index_id,
-            source_id: "void-source".to_string(),
+            source_id: "vec-source".to_string(),
```
Comment (guilload) [inline quickwit-indexing/src/actors/indexing_server.rs:323]: The void source is better for those tests because, with a vec source, the whole pipeline can finish before we observe it running.

File: quickwit-indexing/src/actors/indexing_server.rs [hunk 4]
```diff
@@ -544,6 +544,29 @@ mod tests {
         client.spawn_pipelines(index_id.clone()).await.unwrap();
         assert_eq!(client.observe_server().await.num_running_pipelines, 2);
 
+        // Test `spawn_merge_pipeline`.
+        let merge_pipeline_id = client
+            .spawn_merge_pipeline(index_id.clone(), true, false)
+            .await
+            .unwrap();
+        assert_eq!(client.observe_server().await.num_running_pipelines, 3);
+        assert_eq!(
```
Comment (guilload) [inline quickwit-indexing/src/actors/indexing_server.rs:553]: `.observe_pipeline` is fairly slow. Let's store the observation in one variable and perform the two asserts on the same observation.

File: quickwit-indexing/src/models/indexing_statistics.rs [hunk 5]
```diff
@@ -40,6 +40,10 @@ pub struct IndexingStatistics {
     pub total_bytes_processed: u64,
     /// Size in bytes of resulting split
     pub total_size_splits: u64,
+    /// Pipeline generation.
+    pub generation: usize,
+    /// Number of pipeline spawn successive attempts.
```
Comment (guilload) [inline quickwit-indexing/src/models/indexing_statistics.rs:45]:
```suggestion
    /// Number of successive pipeline spawn attempts.
```

**Review by guilload — APPROVED** [review]

File: quickwit-indexing/src/actors/indexing_pipeline.rs (hunk 2 above)
Comment (fmassot) [reply quickwit-indexing/src/actors/indexing_pipeline.rs:447]: my bad, I should have cleaned that too :/

File: quickwit-indexing/src/actors/indexing_pipeline.rs [hunk 6]
```diff
@@ -126,10 +126,9 @@ impl IndexingPipeline {
                     &*indexer_counters,
                     &*uploader_counters,
                     &*publisher_counters,
-                );
-        } else {
-            ctx.send_self_message(IndexingPipelineMessage::Spawn { retry_count: 0 })
```
Comment (fmassot) [inline quickwit-indexing/src/actors/indexing_pipeline.rs:131]: sending here the self message is not working
