### PR TITLE
Finalize, override exit status on finalize error and then exit.

### LINKED ISSUE #766: Indexer panics when the source is exhausted
When the source ends, it exits successfully but then the indexer panicks just after. Kill switch is activated and then the pipeline is restarted.

```
quickwit git:(demux-job) ✗ cargo r --release index --index-id hdfs_logs --metastore-uri file://Users/fmassot/Documents/quickwit/repos/quickwit-2/indexes --source-config-path ../quickwit-2/hdfs_source_config.json --data-dir-path datadir
    Finished release [optimized] target(s) in 0.47s
     Running `target/release/quickwit index --index-id hdfs_logs --metastore-uri 'file://Users/fmassot/Documents/quickwit/repos/quickwit-2/indexes' --source-config-path ../quickwit-2/hdfs_source_config.json --data-dir-path datadir`
2021-11-12T11:58:48.769+00:00  INFO quickwit: version="0.1.0" commit="a14f8d3"
2021-11-12T11:58:48.776+00:00  INFO {index=hdfs_logs gen=0}: quickwit_indexing::actors::pipeline_supervisor: spawn-indexing-pipeline root_dir=datadir/hdfs_logs merge_policy=StableMultitenantWithTimestampMergePolicy { max_merge_docs: 1000000, min_level_num_docs: 10000, merge_factor: 10, merge_factor_max: 12, demux_factor: 6, demux_field_name: Some("tenant_id"), merge_enabled: true, demux_enabled: false }
2021-11-12T11:58:48.778+00:00  INFO {index=hdfs_logs gen=0}:{actor=GarbageCollector}: quickwit_indexing::actors::garbage_collector: garbage-collect-operation
2021-11-12T11:58:48.834+00:00  INFO {index=hdfs_logs gen=0}:{actor=Indexer}:{msg_id=1}: quickwit_indexing::actors::indexer: new-split split_id=01FMA07EYBCTM0C82ZECCSMDH2
 Num docs   97591 Parse errs     0 PublSplits   0 Input size    36MB Thrghput 35.87MB/s Time 00:00:01
 Num docs   97591 Parse errs     0 PublSplits   0 Input size    36MB Thrghput 17.99MB/s Time 00:00:02
 Num docs  212111 Parse errs     0 PublSplits   0 Input size    78MB Thrghput 26.12MB/s Time 00:00:03
 Num docs  322601 Parse errs     0 PublSplits   0 Input size   119MB Thrghput 29.84MB/s Time 00:00:04
 Num docs  435730 Parse errs     0 PublSplits   0 Input size   161MB Thrghput 31.40MB/s Time 00:00:05
 Num docs  548707 Parse errs     0 PublSplits   0 Input size   203MB Thrghput 41.88MB/s Time 00:00:06
 Num docs  658295 Parse errs     0 PublSplits   0 Input size   244MB Thrghput 41.40MB/s Time 00:00:07
 Num docs  768303 Parse errs     0 PublSplits   0 Input size   284MB Thrghput 41.19MB/s Time 00:00:08
 Num docs  877438 Parse errs     0 PublSplits   0 Input size   324MB Thrghput 40.75MB/s Time 00:00:09
2021-11-12T11:58:57.993+00:00  INFO {index=hdfs_logs gen=0}:{actor=Indexer}:{msg_id=749}: quickwit_indexing::actors::indexer: send-to-packager commit_trigger=NumDocsLimit split="01FMA07EYBCTM0C82ZECCSMDH2" num_docs=1000244
2021-11-12T11:58:57.993+00:00  INFO {index=hdfs_logs gen=0}:{actor=Packager}:{msg_id=46 split_ids=["01FMA07EYBCTM0C82ZECCSMDH2"]}: quickwit_indexing::actors::packager: commit-split
2021-11-12T11:58:58.074+00:00  INFO {index=hdfs_logs gen=0}:{actor=Indexer}:{msg_id=750}: quickwit_indexing::actors::indexer: new-split split_id=01FMA07QY9ZJJEF0ZHEPDR5NRE
2021-11-12T11:58:58.629+00:00  INFO {index=hdfs_logs gen=0}:{actor=FileSource}:{msg_id=772}: quickwit_indexing::source::file_source: EOF
2021-11-12T11:58:58.641+00:00  INFO {index=hdfs_logs gen=0}:{actor=FileSource}: quickwit_actors::async_actor: actor-exit actor_name="FileSource-icy-KzfS" exit_status=Success
2021-11-12T11:58:58.771+00:00  INFO {index=hdfs_logs gen=0}:{actor=Indexer}: quickwit_actors::sync_actor: exit exit_status=Success
2021-11-12T11:58:58.771+00:00  INFO {index=hdfs_logs gen=0}:{actor=Indexer}: quickwit_indexing::actors::indexer: send-to-packager commit_trigger=NoMoreDocs split="01FMA07QY9ZJJEF0ZHEPDR5NRE" num_docs=44977
 Num docs  984082 Parse errs     0 PublSplits   0 Input size   364MB Thrghput 40.12MB/s Time 00:00:10
2021-11-12T11:58:58.851+00:00 ERROR {index=hdfs_logs gen=0}:{msg_id=71}: quickwit_actors::actor_handle: actor-exit-without-success actor="Indexer-weathered-jdx4" exit_status=Panicked
2021-11-12T11:58:58.851+00:00 ERROR {index=hdfs_logs gen=0}:{msg_id=71}: quickwit_indexing::actors::pipeline_supervisor: indexing pipeline error. healthy=["Packager-falling-AKV9", "Uploader-blue-Aifh", "Publisher-twilight-PmW9", "GarbageCollector-icy-fhe5", "MergePlanner-damp-ia5w", "MergeSplitDownloader-twilight-iRYj", "MergeExecutor-bold-fPvi", "MergePackager-sparkling-CGsd", "MergeUploader-holy-uWKT", "MergePublisher-broken-oSEZ"] failure_or_unhealthy_actors=["Indexer-weathered-jdx4"] success=["FileSource-icy-KzfS"]
2021-11-12T11:58:58.851+00:00  WARN {index=hdfs_logs gen=0}:{msg_id=71}: quickwit_actors::kill_switch: kill-switch-activated
2021-11-12T11:58:58.851+00:00  WARN {index=hdfs_logs gen=0}:{msg_id=71}: quickwit_actors::kill_switch: kill-switch-activated
2021-11-12T11:58:58.851+00:00  WARN {index=hdfs_logs gen=0}:{msg_id=71}: quickwit_actors::kill_switch: kill-switch-activated
2021-11-12T11:58:58.851+00:00  WARN {index=hdfs_logs gen=0}:{msg_id=71}: quickwit_actors::kill_switch: kill-switch-activated
2021-11-12T11:58:58.851+00:00  WARN {index=hdfs_logs gen=0}:{msg_id=71}: quickwit_actors::kill_switch: kill-switch-activated
2021-11-12T11:58:58.851+00:00  WARN {index=hdfs_logs gen=0}:{msg_id=71}: quickwit_actors::kill_switch: kill-switch-activated
2021-11-12T11:58:58.851+00:00  WARN {index=hdfs_logs gen=0}:{msg_id=71}: quickwit_actors::kill_switch: kill-switch-activated
2021-11-12T11:58:58.851+00:00  WARN {index=hdfs_logs gen=0}:{msg_id=71}: quickwit_actors::kill_switch: kill-switch-activated
2021-11-12T11:58:58.851+00:00  WARN {index=hdfs_logs gen=0}:{msg_id=71}: quickwit_actors::kill_switch: kill-switch-activated
2021-11-12T11:58:58.851+00:00  WARN {index=hdfs_logs gen=0}:{msg_id=71}: quickwit_actors::kill_switch: kill-switch-activated
2021-11-12T11:58:58.851+00:00  WARN {index=hdfs_logs gen=0}:{msg_id=71}: quickwit_actors::kill_switch: kill-switch-activated
2021-11-12T11:58:58.851+00:00  WARN {index=hdfs_logs gen=0}:{msg_id=71}: quickwit_actors::kill_switch: kill-switch-activated
2021-11-12T11:58:58.851+00:00  WARN {index=hdfs_logs gen=0}:{msg_id=71}: quickwit_actors::kill_switch: kill-switch-activated
2021-11-12T11:58:58.851+00:00  INFO {index=hdfs_logs gen=0}:{actor=Uploader}: quickwit_actors::async_actor: actor-exit actor_name="Uploader-blue-Aifh" exit_status=Killed
2021-11-12T11:58:58.851+00:00  INFO {index=hdfs_logs gen=0}:{actor=MergeSplitDownloader}: quickwit_actors::async_actor: actor-exit actor_name="MergeSplitDownloader-twilight-iRYj" exit_status=Killed
2021-11-12T11:58:58.851+00:00  INFO {index=hdfs_logs gen=0}:{actor=Publisher}: quickwit_actors::async_actor: actor-exit actor_name="Publisher-twilight-PmW9" exit_status=Killed
2021-11-12T11:58:58.851+00:00  INFO {index=hdfs_logs gen=0}:{actor=GarbageCollector}: quickwit_actors::async_actor: actor-exit actor_name="GarbageCollector-icy-fhe5" exit_status=Killed
2021-11-12T11:58:58.851+00:00  INFO {index=hdfs_logs gen=0}:{actor=MergePlanner}: quickwit_actors::sync_actor: exit exit_status=Killed
2021-11-12T11:58:58.851+00:00  INFO {index=hdfs_logs gen=0}:{actor=MergePublisher}: quickwit_actors::async_actor: actor-exit actor_name="MergePublisher-broken-oSEZ" exit_status=Killed
2021-11-12T11:58:58.851+00:00  INFO {index=hdfs_logs gen=0}:{actor=MergeUploader}: quickwit_actors::async_actor: actor-exit actor_name="MergeUploader-holy-uWKT" exit_status=Killed
2021-11-12T11:58:58.915+00:00 ERROR {index=hdfs_logs gen=0}:{actor=Packager}: quickwit_actors::actor: exit activating-kill-switch actor=Packager-falling-AKV9 exit_status=Failure(Commit split `IndexedSplit { id: "01FMA07EYBCTM0C82ZECCSMDH2", dir: "/Users/fmassot/Documents/quickwit/repos/quickwit/datadir/hdfs_logs/scratch/split-01FMA07EYBCTM0C82ZECCSMDH2-eEDNuj" }` failed

Caused by:
    0: An IO error occurred: 'Directory kill switch was activated.'
    1: Directory kill switch was activated.)
2021-11-12T11:58:58.915+00:00  WARN {index=hdfs_logs gen=0}:{actor=Packager}: quickwit_actors::kill_switch: kill-switch-activated
2021-11-12T11:58:58.916+00:00  INFO {index=hdfs_logs gen=0}:{actor=Packager}: quickwit_actors::sync_actor: exit exit_status=Failure(cause=Commit split `IndexedSplit { id: "01FMA07EYBCTM0C82ZECCSMDH2", dir: "/Users/fmassot/Documents/quickwit/repos/quickwit/datadir/hdfs_logs/scratch/split-01FMA07EYBCTM0C82ZECCSMDH2-eEDNuj" }` failed

Caused by:
    0: An IO error occurred: 'Directory kill switch was activated.'
    1: Directory kill switch was activated.)
2021-11-12T11:58:58.919+00:00 ERROR {index=hdfs_logs gen=0}:{actor=Indexer}: quickwit_actors::sync_actor: Finalizing failed error=The channel is closed.
2021-11-12T11:58:58.932+00:00  INFO {index=hdfs_logs gen=0}:{actor=MergePackager}: quickwit_actors::sync_actor: exit exit_status=Killed
2021-11-12T11:58:58.935+00:00  INFO {index=hdfs_logs gen=0}:{actor=MergeExecutor}: quickwit_actors::sync_actor: exit exit_status=Killed
 Num docs  984082 Parse errs     0 PublSplits   0 Input size   364MB Thrghput 30.03MB/s Time 00:00:11
2021-11-12T11:58:59.946+00:00  INFO {index=hdfs_logs gen=0}:{msg_id=78}: quickwit_indexing::actors::pipeline_supervisor: spawn-indexing-pipeline root_dir=datadir/hdfs_logs merge_policy=StableMultitenantWithTimestampMergePolicy { max_merge_docs: 1000000, min_level_num_docs: 10000, merge_factor: 10, merge_factor_max: 12, demux_factor: 6, demux_field_name: Some("tenant_id"), merge_enabled: true, demux_enabled: false }
2021-11-12T11:58:59.950+00:00  INFO {index=hdfs_logs gen=0}:{msg_id=78}:{actor=GarbageCollector}: quickwit_indexing::actors::garbage_collector: garbage-collect-operation
2021-11-12T11:59:00.008+00:00  INFO {index=hdfs_logs gen=0}:{msg_id=78}:{actor=Indexer}:{msg_id=1}: quickwit_indexing::actors::indexer: new-split split_id=01FMA07SVF4JQVBX1VN82QEDZ4
 Num docs  984082 Parse errs     0 PublSplits   0 Input size   364MB Thrghput 20.01MB/s Time 00:00:12
 Num docs 1068221 Parse errs     0 PublSplits   0 Input size   395MB Thrghput 17.65MB/s Time 00:00:13
 Num docs 1178706 Parse errs     0 PublSplits   0 Input size   436MB Thrghput 18.02MB/s Time 00:00:14
 Num docs 1290475 Parse errs     0 PublSplits   0 Input size   477MB Thrghput 28.41MB/s Time 00:00:15
 Num docs 1402245 Parse errs     0 PublSplits   0 Input size   519MB Thrghput 38.77MB/s Time 00:00:16
 Num docs 1512569 Parse errs     0 PublSplits   0 Input size   560MB Thrghput 41.25MB/s Time 00:00:17
 Num docs 1622999 Parse errs     0 PublSplits   0 Input size   601MB Thrghput 41.29MB/s Time 00:00:18
 Num docs 1730819 Parse errs     0 PublSplits   0 Input size   640MB Thrghput 40.60MB/s Time 00:00:19
 Num docs 1834575 Parse errs     0 PublSplits   0 Input size   678MB Thrghput 39.89MB/s Time 00:00:20
2021-11-12T11:59:09.385+00:00  INFO {index=hdfs_logs gen=0}:{msg_id=78}:{actor=Indexer}:{msg_id=749}: quickwit_indexing::actors::indexer: send-to-packager commit_trigger=NumDocsLimit split="01FMA07SVF4JQVBX1VN82QEDZ4" num_docs=1000244
2021-11-12T11:59:09.385+00:00  INFO {index=hdfs_logs gen=0}:{msg_id=78}:{actor=Packager}:{msg_id=47 split_ids=["01FMA07SVF4JQVBX1VN82QEDZ4"]}: quickwit_indexing::actors::packager: commit-split
2021-11-12T11:59:09.443+00:00  INFO {index=hdfs_logs gen=0}:{msg_id=78}:{actor=Indexer}:{msg_id=750}: quickwit_indexing::actors::indexer: new-split split_id=01FMA08329N4PHW46AFQQNJ1N9
 Num docs 1938438 Parse errs     0 PublSplits   0 Input size   717MB Thrghput 39.27MB/s Time 00:00:21
2021-11-12T11:59:10.000+00:00  INFO {index=hdfs_logs gen=0}:{msg_id=78}:{actor=FileSource}:{msg_id=772}: quickwit_indexing::source::file_source: EOF
2021-11-12T11:59:10.013+00:00  INFO {index=hdfs_logs gen=0}:{msg_id=78}:{actor=FileSource}: quickwit_actors::async_actor: actor-exit actor_name="FileSource-cool-YP9A" exit_status=Success
2021-11-12T11:59:10.142+00:00  INFO {index=hdfs_logs gen=0}:{msg_id=78}:{actor=Indexer}: quickwit_actors::sync_actor: exit exit_status=Success
2021-11-12T11:59:10.142+00:00  INFO {index=hdfs_logs gen=0}:{msg_id=78}:{actor=Indexer}: quickwit_indexing::actors::indexer: send-to-packager commit_trigger=NoMoreDocs split="01FMA08329N4PHW46AFQQNJ1N9" num_docs=44977
 Num docs 2008551 Parse errs     0 PublSplits   0 Input size   743MB Thrghput 35.52MB/s Time 00:00:22
2021-11-12T11:59:10.915+00:00  INFO {index=hdfs_logs gen=0}:{msg_id=78}:{actor=Packager}:{msg_id=47 split_ids=["01FMA07SVF4JQVBX1VN82QEDZ4"]}: quickwit_indexing::actors::packager: create-packaged-split
2021-11-12T11:59:10.986+00:00 ERROR {index=hdfs_logs gen=0}:{msg_id=149}: quickwit_actors::actor_handle: actor-exit-without-success actor="Indexer-fragrant-WBlt" exit_status=Panicked
2021-11-12T11:59:10.986+00:00 ERROR {index=hdfs_logs gen=0}:{msg_id=149}: quickwit_indexing::actors::pipeline_supervisor: indexing pipeline error. healthy=["Packager-patient-oxst", "Uploader-billowing-Gn0I", "Publisher-hidden-QO26", "GarbageCollector-divine-q3sj", "MergePlanner-weathered-bbkW", "MergeSplitDownloader-wild-hSTb", "MergeExecutor-wandering-fGCn", "MergePackager-frosty-Dsx8", "MergeUploader-shy-WvO0", "MergePublisher-morning-tkg8"] failure_or_unhealthy_actors=["Indexer-fragrant-WBlt"] success=["FileSource-cool-YP9A"]
2021-11-12T11:59:10.986+00:00  WARN {index=hdfs_logs gen=0}:{msg_id=149}: quickwit_actors::kill_switch: kill-switch-activated
```

In debug mode, we have:

```
2021-11-12T12:10:12.077+00:00  INFO {index=hdfs_logs gen=0}:{actor=Indexer}: quickwit_actors::sync_actor: exit exit_status=Success
2021-11-12T12:10:12.077+00:00  INFO {index=hdfs_logs gen=0}:{actor=Indexer}: quickwit_indexing::actors::indexer: send-to-packager commit_trigger=NoMoreDocs split="01FMA0W9DM3C5YWD7XSMQKR9NF" num_docs=44977
2021-11-12T12:10:12.077+00:00 DEBUG {index=hdfs_logs gen=0}:{actor=Indexer}: quickwit_actors::actor: send from=Indexer-misty-NXVo to=Packager-young-yl78 msg=IndexedSplitBatch { splits: [IndexedSplit { id: "01FMA0W9DM3C5YWD7XSMQKR9NF", dir: "/Users/fmassot/Documents/quickwit/repos/quickwit/datadir/hdfs_logs/scratch/split-01FMA0W9DM3C5YWD7XSMQKR9NF-q07JEI" }] }
2021-11-12T12:10:12.593+00:00 DEBUG tantivy::indexer::segment_writer: fastfield-serialize
2021-11-12T12:10:12.594+00:00 DEBUG tantivy::fastfield::serializer: choosing fast field codec Bitpacked for field_id Field(1)
2021-11-12T12:10:12.634+00:00 DEBUG tantivy::fastfield::serializer: choosing fast field codec Bitpacked for field_id Field(2)
2021-11-12T12:10:12.665+00:00 DEBUG tantivy::indexer::segment_writer: resort-docstore
2021-11-12T12:10:12.665+00:00 DEBUG tantivy::indexer::segment_writer: serializer-close
 Num docs 1032571 Parse errs     0 PublSplits   0 Input size   382MB Thrghput 28.00MB/s Time 00:00:14
2021-11-12T12:10:12.902+00:00  INFO {index=hdfs_logs gen=0}:{actor=Packager}:{msg_id=62 split_ids=["01FMA0VX79WM0K2MWRFP93JMW2"]}: tantivy::indexer::index_writer: Prepared commit 1000245
2021-11-12T12:10:12.902+00:00  INFO {index=hdfs_logs gen=0}:{actor=Packager}:{msg_id=62 split_ids=["01FMA0VX79WM0K2MWRFP93JMW2"]}: tantivy::indexer::prepared_commit: committing 1000245
2021-11-12T12:10:12.902+00:00  INFO tantivy::indexer::segment_updater: save metas
2021-11-12T12:10:12.902+00:00 DEBUG tantivy::directory::mmap_directory: Atomic Write "meta.json"
2021-11-12T12:10:12.921+00:00 DEBUG tantivy::indexer::segment_updater: Saved metas Ok("{\n  \"index_settings\": {\n    \"docstore_compression\": \"lz4\"\n  },\n  \"segments\": [\n    {\n      \"segment_id\": \"a133d4ab-f3db-4b8f-8f88-17b2d3bbdfb1\",\n      \"max_doc\": 1000244,\n      \"deletes\": null\n    }\n  ],\n  \"schema\": [\n    {\n      \"name\": \"_tags\",\n      \"type\": \"text\",\n      \"options\": {\n        \"indexing\": {\n          \"record\": \"basic\",\n          \"tokenizer\": \"raw\"\n        },\n        \"stored\": false\n      }\n    },\n    {\n      \"name\": \"timestamp\",\n      \"type\": \"i64\",\n      \"options\": {\n        \"indexed\": true,\n        \"fast\": \"single\",\n        \"stored\": true\n      }\n    },\n    {\n      \"name\": \"tenant_id\",\n      \"type\": \"u64\",\n      \"options\": {\n        \"indexed\": true,\n        \"fast\": \"single\",\n        \"stored\": true\n      }\n    },\n    {\n      \"name\": \"severity_text\",\n      \"type\": \"text\",\n      \"options\": {\n        \"indexing\": {\n          \"record\": \"basic\",\n          \"tokenizer\": \"default\"\n        },\n        \"stored\": true\n      }\n    },\n    {\n      \"name\": \"body\",\n      \"type\": \"text\",\n      \"options\": {\n        \"indexing\": {\n          \"record\": \"basic\",\n          \"tokenizer\": \"default\"\n        },\n        \"stored\": true\n      }\n    },\n    {\n      \"name\": \"resource.service\",\n      \"type\": \"text\",\n      \"options\": {\n        \"indexing\": {\n          \"record\": \"basic\",\n          \"tokenizer\": \"default\"\n        },\n        \"stored\": true\n      }\n    },\n    {\n      \"name\": \"attributes.class\",\n      \"type\": \"text\",\n      \"options\": {\n        \"indexing\": {\n          \"record\": \"basic\",\n          \"tokenizer\": \"default\"\n        },\n        \"stored\": true\n      }\n    }\n  ],\n  \"opstamp\": 1000245\n}")
2021-11-12T12:10:12.921+00:00  INFO tantivy::indexer::segment_updater: Running garbage collection
2021-11-12T12:10:12.921+00:00  INFO tantivy::directory::managed_directory: Garbage collect
2021-11-12T12:10:12.921+00:00 DEBUG tantivy::directory::mmap_directory: Open Write ".tantivy-meta.lock"
2021-11-12T12:10:12.933+00:00 DEBUG {index=hdfs_logs gen=0}:{msg_id=98}: quickwit_actors::actor: from=Pipeline-wild-0OMn send=Scheduler-rough-CBbT msg=ScheduleEvent { timeout: 1s }
2021-11-12T12:10:12.933+00:00 ERROR {index=hdfs_logs gen=0}:{msg_id=99}: quickwit_actors::actor_handle: actor-exit-without-success actor="Indexer-misty-NXVo" exit_status=Panicked
2021-11-12T12:10:12.933+00:00 ERROR {index=hdfs_logs gen=0}:{msg_id=99}: quickwit_indexing::actors::pipeline_supervisor: indexing pipeline error. healthy=["Packager-young-yl78", "Uploader-bold-njBB", "Publisher-winter-PmHk", "GarbageCollector-delicate-Ynee", "MergePlanner-delicate-2JZb", "MergeSplitDownloader-patient-zoPX", "MergeExecutor-misty-btvP", "MergePackager-lingering-nypW", "MergeUploader-little-N5ob", "MergePublisher-twilight-LLdF"] failure_or_unhealthy_actors=["Indexer-misty-NXVo"] success=["FileSource-lively-rp4v"]
```

### PR DESCRIPTION
**Pull request by fmassot**
Fix #766

### CODE REVIEW

File: quickwit-actors/src/actor_handle.rs [hunk 1]
```diff
@@ -92,6 +93,7 @@ impl<A: Actor> Supervisable for ActorHandle<A> {
         {
             Health::Healthy
         } else {
+            println!("timeout");
```
Comment (fulmicoton) [inline quickwit-actors/src/actor_handle.rs:96]:
```suggestion
```

File: quickwit-actors/src/actor_handle.rs [hunk 2]
```diff
@@ -73,6 +73,7 @@ impl<A: Actor> Supervisable for ActorHandle<A> {
 
     fn health(&self) -> Health {
         let actor_state = self.state();
+        println!("state {:?}", actor_state);
```
Comment (fulmicoton) [inline quickwit-actors/src/actor_handle.rs:76]:
```suggestion
```

**Review by fulmicoton — APPROVED** [review]
